// Run explicitly with Bun; Rust tests use the checked-in generated fixture.
import {mock} from "bun:test";
import {readFileSync,writeFileSync} from "node:fs";
import {join} from "node:path";
mock.module("@0sec/shared",()=>({VERSION:"fixture-version",SEVERITY_RANK:{critical:5,high:4,medium:3,low:2,info:1}}));
const {formatSarif}=await import("../../../../../packages/cli/src/formatters/sarif.ts");
const report=JSON.parse(readFileSync(join(import.meta.dir,"report.json"),"utf8"));
writeFileSync(join(import.meta.dir,"typescript.sarif.json"),formatSarif(report)+"\n");

const {formatMarkdown}=await import("../../../../../packages/cli/src/formatters/markdown.ts");
const markdownReport=JSON.parse(readFileSync(join(import.meta.dir,"markdown-report.json"),"utf8"));
writeFileSync(join(import.meta.dir,"typescript.markdown.md"),formatMarkdown(markdownReport));

const {formatHtml}=await import("../../../../../packages/cli/src/formatters/html.ts");
const htmlReport=JSON.parse(readFileSync(join(import.meta.dir,"html-report.json"),"utf8"));
// Preserve the actual renderer output, normalizing only its wall-clock footer.
writeFileSync(join(import.meta.dir,"typescript.html"),formatHtml(htmlReport).replace(/Generated by 0sec &middot; [^<]+/,"Generated by 0sec &middot; 2026-09-18T00:00:00.000Z\n  "));
