import type { ConsoleSessionSnapshot, HarnessUiEvent, HarnessViewBlock } from "@0/shared";
import { Link } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Markdown } from "./markdown";

export function ConsoleInspector({ snapshot, busy, stagePrompt, onScope, onDrain, onHarness }: { snapshot: ConsoleSessionSnapshot; busy: boolean; stagePrompt: (text: string) => void; onScope: () => void; onDrain: () => void; onHarness: (providerId: string, event: HarnessUiEvent) => void }) {
  const controlsQuery = `?session=${encodeURIComponent(snapshot.session.id)}&return=${encodeURIComponent(`/console/${snapshot.session.id}`)}`;
  const totalTokens = snapshot.usage.inputTokens + snapshot.usage.outputTokens;
  const contextWindow = snapshot.contextWindowTokens ?? snapshot.runtime?.contextWindowTokens;
  return <div className="space-y-7 p-5 text-sm">
    <section className="space-y-3"><h3 className="text-sm font-semibold text-foreground">Model</h3><dl className="grid grid-cols-[auto_1fr] gap-x-3 gap-y-2 text-xs"><dt className="text-muted-foreground">Model</dt><dd className="break-all">{snapshot.runtime?.model ?? "Not set"}</dd>{!snapshot.runtime?.configured && <><dt className="text-muted-foreground">Connection</dt><dd className="text-destructive">Not connected</dd></>}{snapshot.session.autonomyMode !== "standard" && <><dt className="text-muted-foreground">Mode</dt><dd>{snapshot.session.autonomyMode}</dd></>}</dl><details className="text-xs"><summary className="cursor-pointer text-muted-foreground">More</summary><dl className="mt-2 grid grid-cols-[auto_1fr] gap-x-3 gap-y-2"><dt className="text-muted-foreground">Provider</dt><dd>{snapshot.runtime?.providerLabel ?? "Not set"}</dd><dt className="text-muted-foreground">Account</dt><dd className="break-all">{snapshot.runtime?.configured ? snapshot.runtime.connectionIdentity ?? "Connected" : "Not connected"}</dd><dt className="text-muted-foreground">Status</dt><dd>{snapshot.session.status}</dd><dt className="text-muted-foreground">Role</dt><dd>{snapshot.session.role}</dd></dl></details><Button asChild variant="outline" size="sm"><Link to={`/models${controlsQuery}`}>Change model</Link></Button>{snapshot.pendingConfiguration && <div role="status" className="rounded-xl bg-primary/10 p-3 text-xs">Changes apply after the current step.<details className="mt-2"><summary className="cursor-pointer text-muted-foreground">Details</summary><pre className="mt-2 whitespace-pre-wrap break-words">{JSON.stringify(snapshot.pendingConfiguration, null, 2)}</pre></details></div>}</section>
    <section className="space-y-3 pt-2"><h3 className="text-sm font-semibold text-foreground">Allowed targets</h3><div className="text-xs"><div className="text-muted-foreground">Target</div><div className="mt-1 break-all">{snapshot.session.target || "None"}</div></div>{!snapshot.scopeEnforcement.enabled && <p role="status" className="rounded-xl bg-destructive/10 p-3 text-xs text-destructive">Network limits are off. 0 can reach any target.</p>}<div className="text-xs"><div className="text-muted-foreground">Allowed</div><ul className="mt-1 space-y-1">{snapshot.scope?.in_scope?.length ? snapshot.scope.in_scope.map((item) => <li className="break-all" key={item}>{item}</li>) : <li>None</li>}</ul></div><details className="text-xs"><summary className="cursor-pointer text-muted-foreground">More</summary><div className="mt-2 space-y-3"><div><div className="text-muted-foreground">Blocked</div><ul className="mt-1 space-y-1">{snapshot.scope?.out_of_scope?.length ? snapshot.scope.out_of_scope.map((item) => <li className="break-all" key={item}>{item}</li>) : <li>None</li>}</ul></div><div><div className="text-muted-foreground">Allowed folder</div><div className="mt-1 break-all">{snapshot.localScopePath ?? "None"}</div></div><div><div className="text-muted-foreground">Network limits: {snapshot.scopeEnforcement.enabled ? "on" : "off"}</div><p className="mt-1 leading-5">{snapshot.scopeEnforcement.message}</p></div></div></details><Button variant="outline" size="sm" onClick={onScope}>Edit</Button></section>
    <section className="space-y-3 pt-2"><h3 className="text-sm font-semibold text-foreground">Usage</h3><dl className="grid grid-cols-[auto_1fr] gap-2 text-xs"><dt className="text-muted-foreground">Tokens</dt><dd>{totalTokens.toLocaleString()}</dd><dt className="text-muted-foreground">Cost</dt><dd>{typeof snapshot.usage.costUsd === "number" ? `$${snapshot.usage.costUsd.toFixed(2)}${snapshot.usage.costUnavailable ? " (partial)" : ""}` : "Unknown"}</dd></dl>{contextWindow && snapshot.contextInputTokens !== undefined && <progress aria-label="Context used" title="Context used" className="h-2 w-full accent-primary" max={contextWindow} value={snapshot.contextInputTokens} />}<details className="text-xs"><summary className="cursor-pointer text-muted-foreground">More</summary><dl className="mt-2 grid grid-cols-[auto_1fr] gap-2"><dt className="text-muted-foreground">Input tokens</dt><dd>{snapshot.usage.inputTokens.toLocaleString()}</dd><dt className="text-muted-foreground">Output tokens</dt><dd>{snapshot.usage.outputTokens.toLocaleString()}</dd><dt className="text-muted-foreground">Context</dt><dd>{snapshot.contextInputTokens?.toLocaleString() ?? "—"}{contextWindow ? ` / ${contextWindow.toLocaleString()}` : ""}</dd><dt className="text-muted-foreground">Exact cost</dt><dd>{typeof snapshot.usage.costUsd === "number" ? `$${snapshot.usage.costUsd.toFixed(4)} (${snapshot.usage.costKind ?? "estimated"})` : "Unknown"}</dd>{snapshot.lastOutcome && <><dt className="text-muted-foreground">Last step tokens</dt><dd>{snapshot.lastOutcome.budget.tokensUsed.toLocaleString()} / {snapshot.lastOutcome.budget.tokenBudget?.toLocaleString() ?? "unlimited"}</dd><dt className="text-muted-foreground">Tool calls</dt><dd>{snapshot.lastOutcome.budget.iterations} / {snapshot.lastOutcome.budget.maxToolIterations}</dd><dt className="text-muted-foreground">Stopped because</dt><dd>{snapshot.lastOutcome.stopReason}</dd></>}</dl>{snapshot.compaction !== null && <details className="mt-2"><summary className="cursor-pointer text-muted-foreground">Summary of older messages</summary><pre className="mt-2 whitespace-pre-wrap break-words">{JSON.stringify(snapshot.compaction, null, 2)}</pre></details>}</details></section>
    <section className="space-y-3 pt-2"><h3 className="text-sm font-semibold text-foreground">Plan{snapshot.todos ? ` · ${snapshot.todos.done}/${snapshot.todos.total}` : ""}</h3>{snapshot.objective && <p className="whitespace-pre-wrap text-xs leading-5">{snapshot.objective}</p>}{snapshot.todos ? <ol className="space-y-2">{snapshot.todos.todos.map((todo) => <li key={todo.id} className={`rounded-xl bg-muted/30 p-3 text-xs ${todo.status === "completed" || todo.status === "cancelled" ? "text-muted-foreground line-through" : ""}`}>{todo.content}</li>)}</ol> : !snapshot.objective && <p className="text-xs text-muted-foreground">No plan yet.</p>}</section>
    {snapshot.workers.length > 0 && <section className="space-y-3 pt-2"><h3 className="text-sm font-semibold text-foreground">Sub-agents</h3>{snapshot.workers.map((worker) => <Link key={worker.id} className="block rounded-xl bg-muted/30 p-3 text-xs transition-colors hover:bg-muted/60 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring/40" to={`/console/${snapshot.session.id}?worker=${encodeURIComponent(worker.id)}`}><div className="font-medium">{worker.name}</div></Link>)}<Button size="sm" variant="outline" disabled={!snapshot.workers.some((worker) => ["running", "queued", "parked"].includes(worker.status))} onClick={onDrain}>Stop all</Button></section>}
    <section className="space-y-3 pt-2">
      <h3 className="text-sm font-semibold text-foreground">{snapshot.harness?.label || "Extensions"}</h3>
      {snapshot.harness ? <>
        {snapshot.harness.error && <p role="alert" className="text-xs text-destructive">{snapshot.harness.error}</p>}
        {snapshot.harness.views.map(({ providerId, view }) => <div key={providerId} className="space-y-3 rounded-xl bg-muted/30 p-3"><div className="text-xs font-medium">{view.title}</div>{view.blocks.map((block, index) => <HarnessBlock key={index} block={block} stagePrompt={stagePrompt} />)}</div>)}
        {snapshot.harness.commands.map((command) => <div key={`${command.providerId}:${command.id}`} className="space-y-1"><Button className="w-full justify-start" variant="outline" size="sm" disabled={busy || snapshot.session.status !== "ready" || !snapshot.harness?.generationId} onClick={() => onHarness(command.providerId, { kind: "command", id: command.id })}>{command.label}</Button>{command.description && <p className="text-xs leading-5 text-muted-foreground">{command.description}</p>}</div>)}
        {snapshot.harness.settings.map((setting) => <label key={`${snapshot.harness?.generationId}:${setting.providerId}:${setting.id}`} className="block space-y-2 rounded-xl bg-muted/30 p-3 text-xs"><span className="font-medium">{setting.label}</span>{setting.description && <span className="block text-muted-foreground">{setting.description}</span>}{setting.type === "boolean" ? <input type="checkbox" className="accent-primary" checked={Boolean(setting.value)} disabled={busy || snapshot.session.status !== "ready" || !snapshot.harness?.generationId} onChange={(event) => onHarness(setting.providerId, { kind: "setting", id: setting.id, value: event.target.checked })} /> : setting.type === "select" ? <select className="w-full rounded-xl border border-transparent bg-muted/40 p-2 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring/40" value={String(setting.value)} disabled={busy || snapshot.session.status !== "ready" || !snapshot.harness?.generationId} onChange={(event) => onHarness(setting.providerId, { kind: "setting", id: setting.id, value: event.target.value })}>{setting.options?.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select> : <input className="w-full rounded-xl border border-transparent bg-muted/40 p-2 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring/40" defaultValue={String(setting.value)} disabled={busy || snapshot.session.status !== "ready" || !snapshot.harness?.generationId} onBlur={(event) => { if (event.target.value !== setting.value) onHarness(setting.providerId, { kind: "setting", id: setting.id, value: event.target.value }); }} />}</label>)}
        <details className="text-xs"><summary className="rounded-lg focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring/40 cursor-pointer text-muted-foreground">More</summary><p className="mt-2 text-muted-foreground">{snapshot.harness.status} · {snapshot.harness.trusted ? "Trusted" : "Sandboxed"}</p><pre className="mt-2 max-h-96 overflow-auto whitespace-pre-wrap break-words">{JSON.stringify({ providers: snapshot.harness.providers, commands: snapshot.harness.commands, settings: snapshot.harness.settings }, null, 2)}</pre></details>
      </> : <p className="text-xs text-muted-foreground">Not ready yet.</p>}
    </section>
    <details className="space-y-2 pt-2"><summary className="cursor-pointer text-sm font-semibold text-foreground">Tools · {snapshot.tools.length}</summary><div className="mt-2 space-y-2">{snapshot.tools.map((tool) => <details key={tool.name} className="rounded-xl bg-muted/30 p-3 text-xs"><summary className="rounded-lg focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring/40 cursor-pointer font-mono">{tool.name}</summary><p className="mt-2 leading-5 text-muted-foreground">{tool.description}</p><pre className="mt-2 max-h-72 overflow-auto whitespace-pre-wrap break-words">{JSON.stringify(tool.inputSchema, null, 2)}</pre></details>)}</div></details>
  </div>;
}

function HarnessBlock({ block, stagePrompt }: { block: HarnessViewBlock; stagePrompt: (text: string) => void }) {
  if (block.type === "markdown") return <Markdown text={block.text} />;
  if (block.type === "text") return <p className="whitespace-pre-wrap text-xs leading-5">{block.text}</p>;
  if (block.type === "progress") return <div className="text-xs"><div>{block.label} · {block.value} / {block.max}</div><progress className="mt-1 h-2 w-full accent-primary" max={block.max} value={block.value} /></div>;
  if (block.type === "action") return <Button variant="outline" size="sm" onClick={() => stagePrompt(block.prompt)}>{block.label}</Button>;
  return <div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead><tr>{block.columns.map((column, index) => <th key={index} className="p-1">{column}</th>)}</tr></thead><tbody>{block.rows.map((row, index) => <tr key={index}>{row.map((cell, cellIndex) => <td className="border-t border-border p-1" key={cellIndex}>{cell}</td>)}</tr>)}</tbody></table></div>;
}
