import type { ConsoleSessionSnapshot, HarnessUiEvent, HarnessViewBlock } from "@0/shared";
import { Link } from "react-router-dom";
import { Check, Circle, Minus } from "lucide-react";
import { LoadingDots } from "./loading-state";
import { Button } from "@/components/ui/button";
import { Select } from "@/components/ui/select";
import { Switch } from "@/components/ui/switch";
import { Markdown } from "./markdown";

export function ConsoleInspector({ snapshot, busy, stagePrompt, onScope, onDrain, onHarness }: { snapshot: ConsoleSessionSnapshot; busy: boolean; stagePrompt: (text: string) => void; onScope: () => void; onDrain: () => void; onHarness: (providerId: string, event: HarnessUiEvent) => void }) {
  const controlsQuery = `?session=${encodeURIComponent(snapshot.session.id)}&return=${encodeURIComponent(`/console/${snapshot.session.id}`)}`;
  const totalTokens = snapshot.usage.inputTokens + snapshot.usage.outputTokens;
  const contextWindow = snapshot.contextWindowTokens ?? snapshot.runtime?.contextWindowTokens;
  const hasScope = Boolean(snapshot.session.target || snapshot.scope?.in_scope?.length || snapshot.scope?.out_of_scope?.length);
  const hasHarnessContent = Boolean(snapshot.harness && (snapshot.harness.error || snapshot.harness.views.length || snapshot.harness.commands.length || snapshot.harness.settings.length));
  return <div className="space-y-6 p-5 text-sm">
    {snapshot.objective && <section className="space-y-2"><h3 className="text-sm font-semibold text-foreground">Objective</h3><p className="whitespace-pre-wrap text-xs leading-5 text-muted-foreground">{snapshot.objective}</p></section>}
    {!!snapshot.todos?.todos.length && <section className="space-y-3"><div className="flex items-center justify-between gap-3"><h3 className="text-sm font-semibold text-foreground">Plan</h3><span className="text-xs text-muted-foreground">{snapshot.todos.done} / {snapshot.todos.total}</span></div><ol className="space-y-3">{snapshot.todos.todos.map(todo => <li key={todo.id} className="flex items-start gap-2.5 text-xs leading-5">
      <span className="mt-0.5 shrink-0 text-muted-foreground" aria-hidden="true">{todo.status === "completed" ? <Check className="size-3.5" /> : todo.status === "cancelled" ? <Minus className="size-3.5" /> : todo.status === "in_progress" ? <LoadingDots className="console-loading-dots-compact" /> : <Circle className="size-3.5" />}</span>
      <span className={todo.status === "completed" || todo.status === "cancelled" ? "text-muted-foreground line-through" : ""}>{todo.content}<span className="sr-only"> · {todo.status.replaceAll("_", " ")}</span></span>
    </li>)}</ol></section>}
    {(snapshot.workspacePath || snapshot.localScopePath) && <section className="space-y-2"><h3 className="text-sm font-semibold">Workspace</h3><p className="break-words text-xs leading-5 text-muted-foreground">{snapshot.workspacePath ?? snapshot.localScopePath}</p></section>}
    <section className="space-y-3"><h3 className="text-sm font-semibold text-foreground">Session</h3><dl className="grid grid-cols-[auto_1fr] gap-x-3 gap-y-2 text-xs"><dt className="text-muted-foreground">Model</dt><dd className="break-all">{snapshot.runtime?.model ?? "Not set"}</dd>{!snapshot.runtime?.configured && <><dt className="text-muted-foreground">Connection</dt><dd className="text-destructive">Not connected</dd></>}<dt className="text-muted-foreground">Mode</dt><dd className="capitalize">{snapshot.session.autonomyMode}</dd></dl><details className="p-3 text-xs"><summary className="cursor-pointer text-muted-foreground">Connection details</summary><dl className="mt-2 grid grid-cols-[auto_1fr] gap-x-3 gap-y-2"><dt className="text-muted-foreground">Provider</dt><dd>{snapshot.runtime?.providerLabel ?? "Not set"}</dd><dt className="text-muted-foreground">Account</dt><dd className="break-all">{snapshot.runtime?.configured ? snapshot.runtime.connectionIdentity ?? "Connected" : "Not connected"}</dd><dt className="text-muted-foreground">Status</dt><dd>{snapshot.session.status}</dd><dt className="text-muted-foreground">Role</dt><dd>{snapshot.session.role}</dd></dl></details><Button asChild variant="outline" size="sm"><Link to={`/models${controlsQuery}`}>Change model</Link></Button>{snapshot.pendingConfiguration && <div role="status" className="rounded-xl bg-primary/10 p-3 text-xs">Changes apply after the current step.<details className="mt-2"><summary className="cursor-pointer text-muted-foreground">Pending configuration</summary><pre className="mt-2 whitespace-pre-wrap break-words">{JSON.stringify(snapshot.pendingConfiguration, null, 2)}</pre></details></div>}</section>
    {hasScope && <section className="space-y-3"><div className="flex items-center justify-between gap-2"><h3 className="text-sm font-semibold text-foreground">Scope</h3><Button variant="ghost" size="sm" disabled={busy} onClick={onScope}>Edit scope</Button></div>
      {snapshot.session.target && <p className="break-words text-xs leading-5">{snapshot.session.target}</p>}
      {!!snapshot.scope?.in_scope?.length && <div className="text-xs"><p className="text-muted-foreground">Included targets</p><ul className="mt-2 space-y-1">{snapshot.scope.in_scope.map(target => <li key={target} className="break-words">{target}</li>)}</ul></div>}
      {!!snapshot.scope?.out_of_scope?.length && <details className="p-3 text-xs"><summary className="cursor-pointer text-muted-foreground">Excluded targets</summary><ul className="mt-2 space-y-1">{snapshot.scope.out_of_scope.map(target => <li key={target} className="break-words">{target}</li>)}</ul></details>}
    </section>}
    <section className="space-y-3 pt-2"><h3 className="text-sm font-semibold text-foreground">Usage</h3><dl className="grid grid-cols-[auto_1fr] gap-2 text-xs"><dt className="text-muted-foreground">Tokens</dt><dd>{totalTokens.toLocaleString()}</dd><dt className="text-muted-foreground">Cost</dt><dd>{typeof snapshot.usage.costUsd === "number" ? `$${snapshot.usage.costUsd.toFixed(2)}${snapshot.usage.costUnavailable ? " (partial)" : ""}` : "Unknown"}</dd></dl>{contextWindow && snapshot.contextInputTokens !== undefined && <progress aria-label="Context used" title="Context used" className="h-2 w-full accent-primary" max={contextWindow} value={snapshot.contextInputTokens} />}<details className="p-3 text-xs"><summary className="cursor-pointer text-muted-foreground">Token and cost details</summary><dl className="mt-2 grid grid-cols-[auto_1fr] gap-2"><dt className="text-muted-foreground">Input tokens</dt><dd>{snapshot.usage.inputTokens.toLocaleString()}</dd><dt className="text-muted-foreground">Output tokens</dt><dd>{snapshot.usage.outputTokens.toLocaleString()}</dd><dt className="text-muted-foreground">Context</dt><dd>{snapshot.contextInputTokens?.toLocaleString() ?? "—"}{contextWindow ? ` / ${contextWindow.toLocaleString()}` : ""}</dd><dt className="text-muted-foreground">Exact cost</dt><dd>{typeof snapshot.usage.costUsd === "number" ? `$${snapshot.usage.costUsd.toFixed(4)} (${snapshot.usage.costKind ?? "estimated"})` : "Unknown"}</dd>{snapshot.lastOutcome && <><dt className="text-muted-foreground">Last step tokens</dt><dd>{snapshot.lastOutcome.budget.tokensUsed.toLocaleString()} / {snapshot.lastOutcome.budget.tokenBudget?.toLocaleString() ?? "unlimited"}</dd><dt className="text-muted-foreground">Tool calls</dt><dd>{snapshot.lastOutcome.budget.iterations} / {snapshot.lastOutcome.budget.maxToolIterations}</dd><dt className="text-muted-foreground">Stopped because</dt><dd>{snapshot.lastOutcome.stopReason}</dd></>}</dl>{snapshot.compaction !== null && <details className="mt-2"><summary className="cursor-pointer text-muted-foreground">Summary of older messages</summary><pre className="mt-2 whitespace-pre-wrap break-words">{JSON.stringify(snapshot.compaction, null, 2)}</pre></details>}</details></section>
    {snapshot.workers.length > 0 && <section className="space-y-3 pt-2"><h3 className="text-sm font-semibold text-foreground">Agents</h3>{snapshot.workers.map((worker) => <Link key={worker.id} className="block rounded-xl bg-muted/30 p-3 text-xs transition-colors hover:bg-muted/60 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring/40" to={`/console/${snapshot.session.id}?worker=${encodeURIComponent(worker.id)}`}><div className="flex items-center justify-between gap-2"><span className="truncate font-medium">{worker.name}</span><span className="shrink-0 capitalize text-muted-foreground">{worker.status}</span></div><p className="mt-1 line-clamp-2 leading-5 text-muted-foreground">{worker.task}</p></Link>)}<Button size="sm" variant="outline" disabled={!snapshot.workers.some((worker) => ["running", "queued", "parked"].includes(worker.status))} onClick={onDrain}>Stop all</Button></section>}
    {hasHarnessContent && <section className="space-y-3 pt-2">
      <h3 className="text-sm font-semibold text-foreground">{snapshot.harness?.label || "Extensions"}</h3>
      {snapshot.harness ? <>
        {snapshot.harness.error && <p role="alert" className="text-xs text-destructive">{snapshot.harness.error}</p>}
        {snapshot.harness.views.map(({ providerId, view }) => <div key={providerId} className="space-y-3 rounded-xl bg-muted/30 p-3"><div className="text-xs font-medium">{view.title}</div>{view.blocks.map((block, index) => <HarnessBlock key={index} block={block} stagePrompt={stagePrompt} />)}</div>)}
        {snapshot.harness.commands.map((command) => <div key={`${command.providerId}:${command.id}`} className="space-y-1"><Button className="w-full justify-start" variant="outline" size="sm" disabled={busy || snapshot.session.status !== "ready" || !snapshot.harness?.generationId} onClick={() => onHarness(command.providerId, { kind: "command", id: command.id })}>{command.label}</Button>{command.description && <p className="text-xs leading-5 text-muted-foreground">{command.description}</p>}</div>)}
        {snapshot.harness.settings.map((setting) => <label key={`${snapshot.harness?.generationId}:${setting.providerId}:${setting.id}`} className="block space-y-2 rounded-xl bg-muted/30 p-3 text-xs"><span className="font-medium">{setting.label}</span>{setting.description && <span className="block text-muted-foreground">{setting.description}</span>}{setting.type === "boolean" ? <Switch aria-label={setting.label} checked={Boolean(setting.value)} disabled={busy || snapshot.session.status !== "ready" || !snapshot.harness?.generationId} onCheckedChange={value => onHarness(setting.providerId, { kind: "setting", id: setting.id, value })} /> : setting.type === "select" ? <Select aria-label={setting.label} value={String(setting.value)} disabled={busy || snapshot.session.status !== "ready" || !snapshot.harness?.generationId} onValueChange={value => onHarness(setting.providerId, { kind: "setting", id: setting.id, value })} options={setting.options ?? []} /> : <input className="w-full rounded-xl border border-transparent bg-muted/40 p-2 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring/40" defaultValue={String(setting.value)} disabled={busy || snapshot.session.status !== "ready" || !snapshot.harness?.generationId} onBlur={(event) => { if (event.target.value !== setting.value) onHarness(setting.providerId, { kind: "setting", id: setting.id, value: event.target.value }); }} />}</label>)}
        <details className="p-3 text-xs"><summary className="rounded-lg focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring/40 cursor-pointer text-muted-foreground">Extension details</summary><p className="mt-2 text-muted-foreground">{snapshot.harness.status} · {snapshot.harness.trusted ? "Trusted" : "Sandboxed"}</p><pre className="mt-2 max-h-96 overflow-auto whitespace-pre-wrap break-words">{JSON.stringify({ providers: snapshot.harness.providers, commands: snapshot.harness.commands, settings: snapshot.harness.settings }, null, 2)}</pre></details>
      </> : <p className="text-xs text-muted-foreground">Not ready yet.</p>}
    </section>}
    {snapshot.tools.length > 0 && <details className="space-y-2 pt-2"><summary className="cursor-pointer text-sm font-semibold text-foreground">Tools · {snapshot.tools.length}</summary><div className="mt-2 space-y-2">{snapshot.tools.map((tool) => <details key={tool.name} className="rounded-xl bg-muted/30 p-3 text-xs"><summary className="rounded-lg focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring/40 cursor-pointer font-medium">{tool.name}</summary><p className="mt-2 leading-5 text-muted-foreground">{tool.description}</p><pre className="mt-2 max-h-72 overflow-auto whitespace-pre-wrap break-words">{JSON.stringify(tool.inputSchema, null, 2)}</pre></details>)}</div></details>}
  </div>;
}

function HarnessBlock({ block, stagePrompt }: { block: HarnessViewBlock; stagePrompt: (text: string) => void }) {
  if (block.type === "markdown") return <Markdown text={block.text} />;
  if (block.type === "text") return <p className="whitespace-pre-wrap text-xs leading-5">{block.text}</p>;
  if (block.type === "progress") return <div className="text-xs"><div>{block.label} · {block.value} / {block.max}</div><progress className="mt-1 h-2 w-full accent-primary" max={block.max} value={block.value} /></div>;
  if (block.type === "action") return <Button variant="outline" size="sm" onClick={() => stagePrompt(block.prompt)}>{block.label}</Button>;
  return <div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead><tr>{block.columns.map((column, index) => <th key={index} className="p-1">{column}</th>)}</tr></thead><tbody>{block.rows.map((row, index) => <tr key={index}>{row.map((cell, cellIndex) => <td className="border-t border-border p-1" key={cellIndex}>{cell}</td>)}</tr>)}</tbody></table></div>;
}
