[package]
name = "zero-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[[bin]]
name = "0sec-native"
path = "src/main.rs"

[dependencies]
clap.workspace = true
tokio.workspace = true
tokio-util.workspace = true
serde.workspace = true
serde_json.workspace = true
zero-protocol.workspace = true
zero-engine = { path = "../zero-engine" }
zero-executor.workspace = true
zero-provider.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
