import { useState } from "react";
import { ArrowUp, FileUp, Layers, Search, ShieldCheck, Trash2, Workflow } from "lucide-react";
import type { SecurityWorkflow, SecurityWorkflowInput, SecurityWorkflowTemplate } from "@0/shared";
import { SECURITY_WORKFLOW_TEMPLATES } from "@0/shared/dist/security-workflow-templates.js";
import { parseSecurityWorkflowCode, isSecurityWorkflowOperation } from "@0/shared/dist/security-workflows.js";
import { PageHeader } from "@/components/page-header";
import { Tooltip } from "@/components/ui/tooltip";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { WorkflowAutomationControl } from "@/components/workflow-automation-control";
import { TeamPresenceAvatars } from "@/console/team-collaboration";
import type { TeamPresence } from "@/lib/team-client";
import { ActivityIndicator } from "@/console/loading-state";

const TARGET_LABELS: Record<string, string> = { "source-code": "Repository", "npm-package": "npm package", "pypi-package": "Python package", "cargo-package": "Rust crate", "oci-image": "Container image", url: "URL", "web-app": "Web app" };

export function WorkflowLibrary({ readOnly = false, shared = false, presenceById = {}, definitions, busy, onSelect, onTemplate, onImport, onDescribe, onDelete }: { readOnly?: boolean; shared?: boolean; presenceById?: Record<string, TeamPresence[]>; definitions: SecurityWorkflow[]; busy: boolean; onSelect: (id: string) => void; onTemplate: (id: string) => Promise<void>; onImport: (definition: SecurityWorkflowInput) => Promise<void>; onDescribe: (text: string) => void; onDelete: (workflow: SecurityWorkflow, trigger: HTMLButtonElement) => void }) {
  const [tab, setTab] = useState(definitions.length ? "mine" : "templates");
  const [search, setSearch] = useState("");
  const [description, setDescription] = useState("");
  const [template, setTemplate] = useState<SecurityWorkflowTemplate | null>(null);
  const [error, setError] = useState("");
  const [importOpen, setImportOpen] = useState(false);
  const [source, setSource] = useState("");
  const [importError, setImportError] = useState("");
  const matches = (text: string) => text.toLowerCase().includes(search.trim().toLowerCase());
  const saved = definitions.filter(item => matches(`${item.name} ${item.target} ${item.instructions}`));
  const templates = SECURITY_WORKFLOW_TEMPLATES.filter(item => matches(`${item.name} ${item.description} ${item.category}`));
  return <div className="space-y-6">
    <PageHeader title="Workflows" summary="Save steps you can run again." actions={<Button variant="ghost" disabled={busy || readOnly} onClick={() => { setImportError(""); setImportOpen(true); }}><FileUp aria-hidden="true" />Import definition</Button>} />
    <Tabs value={tab} onValueChange={setTab} className="gap-5">
      <div className="flex flex-wrap items-center justify-between gap-4"><TabsList aria-label="Workflow library"><TabsTrigger value="mine">{shared ? "Workspace workflows" : "My workflows"}</TabsTrigger><TabsTrigger value="templates">Templates</TabsTrigger></TabsList><div className="relative w-full sm:w-72"><Search aria-hidden="true" className="pointer-events-none absolute left-3 top-3 size-4 text-muted-foreground" /><Input aria-label="Search workflows and templates" placeholder="Search workflows…" className="pl-9" value={search} onChange={event => setSearch(event.target.value)} /></div></div>
      <TabsContent value="mine"><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{saved.map(item => <article key={item.id} className="group relative flex flex-col gap-5 rounded-2xl bg-muted/35 p-5 transition-colors hover:bg-muted/50"><button type="button" disabled={busy} onClick={() => onSelect(item.id)} className="space-y-3 rounded-lg pr-8 text-left focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-primary"><Workflow aria-hidden="true" className="size-5 text-primary" /><span className="flex items-center justify-between gap-2"><span className="block truncate text-sm font-medium">{item.name}</span><TeamPresenceAvatars compact presence={presenceById[item.id] ?? []} /></span><span className="block truncate text-xs text-muted-foreground">{item.target || "Choose a target"}</span><span className="block text-xs text-muted-foreground">{item.nodes.filter(isSecurityWorkflowOperation).length} steps</span></button><Tooltip content="Delete workflow"><Button variant="ghost" size="icon-sm" aria-label={`Delete ${item.name}`} disabled={busy || readOnly} onClick={event => onDelete(item, event.currentTarget)} className="absolute right-3 top-3 text-muted-foreground opacity-0 transition-opacity hover:bg-destructive/10 hover:text-destructive group-hover:opacity-100 group-focus-within:opacity-100 focus-visible:opacity-100 [@media(hover:none)]:opacity-100"><Trash2 aria-hidden="true" /></Button></Tooltip><div className="mt-auto border-t border-border/40 pt-4"><WorkflowAutomationControl workflow={item} disabled={busy || readOnly} onConfigureTarget={() => onSelect(item.id)} /></div></article>)}</div>{!saved.length && <p className="py-12 text-center text-sm text-muted-foreground">{search ? "No matching workflows." : "Create your first workflow from a template or describe it below."}</p>}</TabsContent>
      <TabsContent value="templates"><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{templates.map(item => <button type="button" key={item.id} disabled={busy || readOnly} onClick={() => { setError(""); setTemplate(item); }} className="flex flex-col items-start gap-3 rounded-2xl bg-muted/35 p-5 text-left transition-colors hover:bg-muted focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-primary"><ShieldCheck aria-hidden="true" className="size-5 text-primary" /><span className="text-sm font-medium">{item.name}</span><span className="text-xs leading-5 text-muted-foreground">{item.description}</span><span className="mt-auto flex items-center gap-1.5 pt-2 text-xs text-muted-foreground"><Layers aria-hidden="true" className="size-3.5" />{item.definition.nodes.filter(isSecurityWorkflowOperation).length} steps · {item.category} · revision {item.revision}</span></button>)}</div>{!templates.length && <p className="py-12 text-center text-sm text-muted-foreground">No matching templates.</p>}</TabsContent>
    </Tabs>
    <section className="mx-auto w-full max-w-3xl pt-3"><h3 className="mb-3 text-sm font-medium">Create a custom workflow</h3><form className="flex items-end gap-3 rounded-[28px] bg-muted px-4 py-3" onSubmit={event => { event.preventDefault(); if (description.trim()) onDescribe(description.trim()); }}><textarea rows={1} aria-label="Describe a custom workflow" placeholder="Describe the steps you want 0 to build…" disabled={busy || readOnly} value={description} className="max-h-48 min-h-7 flex-1 resize-none bg-transparent px-2 py-1 text-sm leading-6 outline-none placeholder:text-muted-foreground" onChange={event => { setDescription(event.target.value); event.target.style.height = "auto"; event.target.style.height = `${Math.min(event.target.scrollHeight, 192)}px`; }} onKeyDown={event => { if (event.key === "Enter" && !event.shiftKey && !event.nativeEvent.isComposing) { event.preventDefault(); if (description.trim()) onDescribe(description.trim()); } }} /><Button type="submit" size="icon-sm" aria-label="Create custom workflow in chat" disabled={busy || !description.trim()}><ArrowUp aria-hidden="true" /></Button></form>{busy && !template && <div className="mt-3"><ActivityIndicator label="Opening workflow…" /></div>}</section>
    <Dialog open={template !== null} onOpenChange={open => { if (!open && !busy) setTemplate(null); }}><DialogContent showCloseButton={!busy} className="sm:max-w-lg"><DialogHeader><DialogTitle>{template?.name}</DialogTitle><DialogDescription>{template?.description}</DialogDescription></DialogHeader><p className="text-xs text-muted-foreground">Template revision {template?.revision} · {template?.executor === "assessment" ? "Security assessment" : template?.executor === "verify" ? "Finding verification" : template?.executor === "fix" ? "Fix candidate and validation" : template?.executor === "research" ? "Security research" : "Deep source review"} · Targets: {template?.compatibleTargetTypes.map(type => TARGET_LABELS[type] ?? type).join(", ")}</p><ul className="space-y-2 text-xs text-muted-foreground">{template?.inputRequirements.map(requirement => <li key={requirement.names.join("|")}>{requirement.required ? "Required: " : "Optional: "}{requirement.description}</li>)}</ul><ol className="space-y-3">{template?.definition.nodes.map((node, index) => <li key={node.id} className="flex gap-3 text-sm"><span className="flex size-6 shrink-0 items-center justify-center rounded-full bg-muted text-xs text-muted-foreground">{index + 1}</span><div><p>{node.label}</p><p className="mt-1 text-xs text-muted-foreground">{node.type === "trigger" ? "Manual trigger" : node.type === "report" ? "Collect results" : node.type === "audit" ? `Assessment · ${node.plan?.runCount ?? 1} attempts` : node.type === "verify" ? "Finding verification" : node.type === "fix" ? "Fix candidate" : node.type === "research" ? "Security research" : "Deep source review"}</p></div></li>)}</ol><p className="text-xs text-muted-foreground">Each step uses its selected operation and validated inputs. Choose a compatible target and adjust steps after saving. Nothing runs until you select Run.</p>{error && <p role="alert" className="text-xs text-destructive">{error}</p>}<DialogFooter><Button variant="ghost" disabled={busy || readOnly} onClick={() => setTemplate(null)}>Cancel</Button><Button disabled={busy || readOnly} onClick={() => { if (template) void onTemplate(template.id).then(() => setTemplate(null)).catch(cause => setError(cause instanceof Error ? cause.message : "Unable to use template.")); }}>{busy ? "Saving…" : "Use template"}</Button></DialogFooter></DialogContent></Dialog>
    <Dialog open={importOpen} onOpenChange={open => { if (!busy) setImportOpen(open); }}><DialogContent showCloseButton={!busy} className="sm:max-w-2xl"><form className="space-y-4" onSubmit={event => { event.preventDefault(); setImportError(""); try { const parsed = parseSecurityWorkflowCode(source); void onImport(parsed).then(() => { setImportOpen(false); setSource(""); }).catch(cause => setImportError(cause instanceof Error ? cause.message : "Unable to import definition.")); } catch (cause) { setImportError(cause instanceof Error ? cause.message : "Invalid workflow definition."); } }}><DialogHeader><DialogTitle>Import definition</DialogTitle><DialogDescription>Paste workflow JSON. Importing creates a new workflow without running it.</DialogDescription></DialogHeader><Textarea aria-label="Workflow JSON to import" placeholder={'{ "schemaVersion": 1, "workflow": { … } }'} spellCheck={false} autoComplete="off" rows={12} className="max-h-[45dvh] min-h-64 resize-y rounded-2xl font-mono text-xs leading-6" disabled={busy || readOnly} value={source} onChange={event => { setSource(event.target.value); setImportError(""); }} />{importError && <p role="alert" className="max-h-24 overflow-y-auto whitespace-pre-wrap text-xs text-destructive">{importError}</p>}<DialogFooter><Button type="button" variant="ghost" disabled={busy || readOnly} onClick={() => setImportOpen(false)}>Cancel</Button><Button type="submit" disabled={busy || !source.trim()}>{busy ? "Importing…" : "Import workflow"}</Button></DialogFooter></form></DialogContent></Dialog>
  </div>;
}
