import { useState } from "react";
import { ArrowUp, FileUp, Layers, Search, ShieldCheck, Workflow } from "lucide-react";
import type { SecurityWorkflow, SecurityWorkflowInput, SecurityWorkflowTemplate } from "@0/shared";
import { SECURITY_WORKFLOW_TEMPLATES } from "@0/shared/dist/security-workflow-templates.js";
import { parseSecurityWorkflowCode } from "@0/shared/dist/security-workflows.js";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { ActivityIndicator } from "@/console/loading-state";

export function WorkflowLibrary({ definitions, busy, onSelect, onTemplate, onImport, onDescribe }: { definitions: SecurityWorkflow[]; busy: boolean; onSelect: (id: string) => void; onTemplate: (id: string) => Promise<void>; onImport: (definition: SecurityWorkflowInput) => Promise<void>; onDescribe: (text: string) => void }) {
  const [tab, setTab] = useState(definitions.length ? "mine" : "templates");
  const [search, setSearch] = useState("");
  const [description, setDescription] = useState("");
  const [template, setTemplate] = useState<SecurityWorkflowTemplate | null>(null);
  const [error, setError] = useState("");
  const [importOpen, setImportOpen] = useState(false);
  const [source, setSource] = useState("");
  const [importError, setImportError] = useState("");
  const matches = (text: string) => text.toLowerCase().includes(search.trim().toLowerCase());
  const saved = definitions.filter(item => matches(`${item.name} ${item.target} ${item.instructions}`));
  const templates = SECURITY_WORKFLOW_TEMPLATES.filter(item => matches(`${item.name} ${item.description} ${item.category}`));
  return <div className="space-y-7">
    <div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="text-2xl font-medium tracking-tight">Workflows</h2><p className="mt-2 text-sm text-muted-foreground">Create your own custom security workflows!</p></div><Button variant="ghost" size="sm" disabled={busy} onClick={() => { setImportError(""); setImportOpen(true); }}><FileUp aria-hidden="true" />Import definition</Button></div>
    <Tabs value={tab} onValueChange={setTab} className="gap-5">
      <div className="flex flex-wrap items-center justify-between gap-4"><TabsList aria-label="Workflow library"><TabsTrigger value="mine">My workflows</TabsTrigger><TabsTrigger value="templates">Templates</TabsTrigger></TabsList><div className="relative w-full sm:w-72"><Search aria-hidden="true" className="pointer-events-none absolute left-3 top-3 size-4 text-muted-foreground" /><Input aria-label="Search workflows and templates" placeholder="Search workflows…" className="pl-9" value={search} onChange={event => setSearch(event.target.value)} /></div></div>
      <TabsContent value="mine"><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{saved.map(item => <button type="button" key={item.id} disabled={busy} onClick={() => onSelect(item.id)} className="space-y-3 rounded-2xl bg-muted/35 p-5 text-left transition-colors hover:bg-muted focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-primary"><Workflow aria-hidden="true" className="size-5 text-primary" /><span className="block truncate text-sm font-medium">{item.name}</span><span className="block truncate text-xs text-muted-foreground">{item.target || "Target not configured"}</span><span className="block text-xs text-muted-foreground">{item.nodes.filter(node => node.type === "audit").length} review phases · Manual trigger</span></button>)}</div>{!saved.length && <p className="py-12 text-center text-sm text-muted-foreground">{search ? "No matching workflows." : "Create your first workflow from a template or describe it below."}</p>}</TabsContent>
      <TabsContent value="templates"><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{templates.map(item => <button type="button" key={item.id} disabled={busy} onClick={() => { setError(""); setTemplate(item); }} className="flex flex-col items-start gap-3 rounded-2xl bg-muted/35 p-5 text-left transition-colors hover:bg-muted focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-primary"><ShieldCheck aria-hidden="true" className="size-5 text-primary" /><span className="text-sm font-medium">{item.name}</span><span className="text-xs leading-5 text-muted-foreground">{item.description}</span><span className="mt-auto flex items-center gap-1.5 pt-2 text-xs text-muted-foreground"><Layers aria-hidden="true" className="size-3.5" />{item.definition.nodes.filter(node => node.type === "audit").length} review phases · {item.category}</span></button>)}</div>{!templates.length && <p className="py-12 text-center text-sm text-muted-foreground">No matching templates.</p>}</TabsContent>
    </Tabs>
    <section className="mx-auto w-full max-w-3xl pt-3"><h3 className="mb-3 text-sm font-medium">Create a custom workflow</h3><form className="flex items-end gap-3 rounded-[28px] bg-muted px-4 py-3" onSubmit={event => { event.preventDefault(); if (description.trim()) onDescribe(description.trim()); }}><textarea rows={1} aria-label="Describe a custom workflow" placeholder="Describe the phases you want 0 to build…" disabled={busy} value={description} className="max-h-48 min-h-7 flex-1 resize-none bg-transparent px-2 py-1 text-sm leading-6 outline-none placeholder:text-muted-foreground" onChange={event => { setDescription(event.target.value); event.target.style.height = "auto"; event.target.style.height = `${Math.min(event.target.scrollHeight, 192)}px`; }} onKeyDown={event => { if (event.key === "Enter" && !event.shiftKey && !event.nativeEvent.isComposing) { event.preventDefault(); if (description.trim()) onDescribe(description.trim()); } }} /><Button type="submit" size="icon-sm" aria-label="Create custom workflow in chat" disabled={busy || !description.trim()}><ArrowUp aria-hidden="true" /></Button></form>{busy && !template && <div className="mt-3"><ActivityIndicator label="Opening workflow…" /></div>}</section>
    <Dialog open={template !== null} onOpenChange={open => { if (!open && !busy) setTemplate(null); }}><DialogContent showCloseButton={!busy} className="sm:max-w-lg"><DialogHeader><DialogTitle>{template?.name}</DialogTitle><DialogDescription>{template?.description}</DialogDescription></DialogHeader><ol className="space-y-3">{template?.definition.nodes.map((node, index) => <li key={node.id} className="flex gap-3 text-sm"><span className="flex size-6 shrink-0 items-center justify-center rounded-full bg-muted text-xs text-muted-foreground">{index + 1}</span><div><p>{node.label}</p><p className="mt-1 text-xs text-muted-foreground">{node.type === "trigger" ? "Start manually" : node.type === "report" ? "Collect results" : `${node.plan?.depth ?? "default"} review · ${node.plan?.runCount ?? 1} runs`}</p></div></li>)}</ol><p className="text-xs text-muted-foreground">Choose a target and adjust phases after saving. Nothing runs until you approve Run.</p>{error && <p role="alert" className="text-xs text-destructive">{error}</p>}<DialogFooter><Button variant="ghost" disabled={busy} onClick={() => setTemplate(null)}>Cancel</Button><Button disabled={busy} onClick={() => { if (template) void onTemplate(template.id).then(() => setTemplate(null)).catch(cause => setError(cause instanceof Error ? cause.message : "Unable to use template.")); }}>{busy ? "Saving…" : "Use template"}</Button></DialogFooter></DialogContent></Dialog>
    <Dialog open={importOpen} onOpenChange={open => { if (!busy) setImportOpen(open); }}><DialogContent showCloseButton={!busy} className="sm:max-w-2xl"><form className="space-y-4" onSubmit={event => { event.preventDefault(); setImportError(""); try { const parsed = parseSecurityWorkflowCode(source); void onImport(parsed).then(() => { setImportOpen(false); setSource(""); }).catch(cause => setImportError(cause instanceof Error ? cause.message : "Unable to import definition.")); } catch (cause) { setImportError(cause instanceof Error ? cause.message : "Invalid workflow definition."); } }}><DialogHeader><DialogTitle>Import definition</DialogTitle><DialogDescription>Paste workflow JSON. Importing creates a new workflow without running it.</DialogDescription></DialogHeader><Textarea aria-label="Workflow JSON to import" placeholder={'{ "schemaVersion": 1, "workflow": { … } }'} spellCheck={false} autoComplete="off" rows={12} className="max-h-[45dvh] min-h-64 resize-y rounded-2xl font-mono text-xs leading-6" disabled={busy} value={source} onChange={event => { setSource(event.target.value); setImportError(""); }} />{importError && <p role="alert" className="max-h-24 overflow-y-auto whitespace-pre-wrap text-xs text-destructive">{importError}</p>}<DialogFooter><Button type="button" variant="ghost" disabled={busy} onClick={() => setImportOpen(false)}>Cancel</Button><Button type="submit" disabled={busy || !source.trim()}>{busy ? "Importing…" : "Import workflow"}</Button></DialogFooter></form></DialogContent></Dialog>
  </div>;
}
