[package]
name = "zero-sandbox"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true
[dependencies]
zero-protocol.workspace = true
zero-executor.workspace = true
zero-smolvm = { path = "../zero-smolvm" }
tokio.workspace = true
tokio-util.workspace = true
[dev-dependencies]
tempfile.workspace = true
serde_json.workspace = true
sha2.workspace = true
[lints]
workspace = true
